# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#-------------------------------------------------------------------------
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  snyk: snyk/snyk@0.0.12
  slack: circleci/slack@4.8.1
  python: circleci/python@1.4.0
slack-fail-post-step: &slack-fail-post-step
  post-steps:
    - slack/notify:
        event: fail
        template: basic_fail_1
executors:
  node-executor:
    docker:
      - image: cimg/node:14.16.0
  browser-executor:
    docker:
      - image: circleci/node:14.16.0-browsers
  e2e-executor:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
        environment:
          NODE_ENV: development
commands:
  git-tag:
    description: "Tag current git commit with 'tag'"
    parameters:
      tag:
        type: string
        default: ""
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f4:e0:5c:97:f2:57:58:a8:e2:c9:c5:b1:78:2e:88:6a"
      - run: |
          git tag -fa "<< parameters.tag >>" -m "<< parameters.tag >>"
          git push -f origin --tags
  lint_commit_message:
    steps:
      - run:
          name: "Verify Commit Message"
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
            echo "$COMMIT_MESSAGE" | npx commitlint
jobs:
  mockedql-to-heroku:
    machine: true
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      # - run:
      #     name: "Update Heroku CLI"
      #     command: heroku update
      # - slack/notify
workflows:
  version: 2
  build-test-and-deploy:
    # Run the build followed by executing the tests and deploy to heroku
    jobs:
      - mockedql-to-heroku:
          context: SLACKAPI
          # requires: 
          #    - build-and-test      
