# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#-------------------------------------------------------------------------
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  snyk: snyk/snyk@0.0.12
  python: circleci/python@1.4.0

executors:
  node-executor:
    docker:
      - image: cimg/node:14.16.0
  browser-executor:
    docker:
      - image: circleci/node:14.16.0-browsers
  e2e-executor:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
        environment:
          NODE_ENV: development


jobs:
  deploy-mockgraphql-to-heroku:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - heroku/install
      - heroku/check-authentication
      - checkout
      - run:
          name: "Set Heroku App name"
          command: |
            pwd
            app_name=$(echo "mockedgraphql-v" | tr / - | cut -c1-24)
            echo "export HEROKU_APP_NAME=$app_name" >> $BASH_ENV
      - run:
          name: "Create app in heroku if it doesn't exist"
          command: |
            [ -z $(heroku apps -t ${HEROKU_TEAM_NAME} -s ${HEROKU_SPACE_NAME} \
                   | grep "${HEROKU_APP_NAME}") ] && (heroku apps:create ${HEROKU_APP_NAME} -t ${HEROKU_TEAM_NAME} \
                   --space=${HEROKU_SPACE_NAME}) \
                   || (echo "Skipping app creation....app ${HEROKU_APP_NAME} already exists")
      - run:
          name: "Create GITHUB_TOKEN environment var if it doesn't exist for the app in heroku"
          command: |
            [ -z $(heroku config:get GITHUB_TOKEN -a ${HEROKU_APP_NAME}) ] \
                   && heroku config:set GITHUB_TOKEN=${GITHUB_TOKEN} -a ${HEROKU_APP_NAME} \
                   || echo "GITHUB_TOKEN already Set.."
      - heroku/deploy-via-git:
          app-name: ${HEROKU_APP_NAME}

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-mockgraphql-to-heroku4
